### ISSUE TITLE
ERROR ~ Error executing process > 'SetPlsdb:FormtPLSDB'

### ISSUE THREAD

**Issue by macarenaalga** [mgimenez720/plaSquid#18]
Hello! I was trying to run plaSquid, and I encountered the following error, both with the test file and a personal one:

`ERROR ~ Error executing process > 'SetPlsdb:FormtPLSDB'

Caused by:
  Process `SetPlsdb:FormtPLSDB` terminated with an error exit status (137)

Command executed:

  minimap2 -d plsdb.mmi plsdb.fna 
  cp plsdb.mmi /home/quimica/Descargas/plaSquid/plsdb.mmi

Command exit status:
  137

Command output:
  (empty)

Command error:
  .command.sh: línea 2: 28242 Terminado (killed)      minimap2 -d plsdb.mmi plsdb.fna

Work dir:
  /home/quimica/Descargas/plaSquid/work/ee/91d92526805223fb350ecc3d088c31

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

`

Upon reviewing the generated output, I noticed that while the plsdb.fna file was created, the plsdb.mmi file has 0 bytes, and I believe this is the cause of the error. I'm not sure if you could provide guidance on how to resolve this issue. 
Regards,
 Macarena.

**Comment by mgimenez720** [comment]
Hello, thank you Macarena for trying plaSquid and giving your feedback.

There was a bug in the conda definition file, bzip2 is needed to decompress plsdb database for building minimap2 database. This is already corrected and hope that now you can use it with no problems. 

When downloading plsdb it is also important to check stable internet connection and to have ~10Gb of free space in the disk, in order to download and format the database correctly.
