### ISSUE TITLE
How to run inside docker image?

### ISSUE THREAD

**Issue by vogdb** [mgimenez720/plaSquid#19]
Hi! I tried to run
```
docker pull mgimenez720/plasquid:latest
docker run --rm -v /data1:/data1 -v /data2:/data2 -v /data:/data  --net=host -it mgimenez720/plasquid
```
The last command gets me inside the docker container but there is no executable `nextflow` there. Can you please advice what is the correct way to use the docker image?

**Comment by mgimenez720** [comment]
Hello! Sorry for the delay in answering, I was out of my office for a conference. I have updated the docker image, so now it should have the nextflow executable, you can try to run it in that way. 

Otherwise, I recommend you to install nextflow natively and use the flag '''-profile docker''' in the following way: '''nextflow run main.nf --contigs {testdata/test.fasta} --outdir {plaSquid_result} -profile docker''' nextflow will use the docker image to resolve the dependencies. Let me know if the problem persists or if you have any other problem.

**Comment by vogdb** [comment]
Thank you!
