### ISSUE TITLE
Fasta headers don't match sequences compared to the input assembly file

### ISSUE THREAD

**Issue by maddne** [mgimenez720/plaSquid#23]
I ran plaSquid (v1.0.0) under WSL2 20.04. Installed with conda.
I have used plaSquid a couple of times on metagenomic assemblies and co-assemblies. So far I haven't noticed anything wrong. For one of my samples though I noticed that some lines in the tsv file are incomplete (hardly noticeable) See the table below.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/KMAR-W~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/KMAR-W~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Contig | name | Sim_dist | plsdb_match | Match_length | RIP_domain | MOB_group | Rep_type | Contig_length
-- | -- | -- | -- | -- | -- | -- | -- | --
ig-27077 | k141_571591 flag=0 multi=56.3714 len=1681 | 75.96669 | CP054199.1 Bacteroides uniformis strain JCM13288 plasmid unnamed1 | 12493 | Rep_3 | NA | NA | 1681
contig-9982 | k141_91538 flag=1 multi=4.0000 len=2000 | 69.68889 | NZ_CP016699.1 Lactococcus lactis subsp. lactis strain 275 plasmid p275A,   complete sequence | 92710 | NA | NA | NA | 2000
contig-9911 | k141_169072 flag=0 multi=18.6759 len=4806 | 83.76667 | NZ_MH830362.1 Enterococcus faecalis plasmid p4, complete sequence | 95693 | NA | NA | NA | 4806
contig-9906 | k141_478531 flag=1 multi=2.0000 len=2064 | 53.55952 | NZ_CP067228.1 Paracoccus sp. MC1862 plasmid unnamed3, complete sequence | 53553 | NA | NA | NA | 2064

</body>

</html>
This was not the bigger issue. I also wanted to manually inspect a putative plasmid of interest within the plasmid fasta file generated by plaSquid and searched with the header but the sequence was different compared to the assembly file. I went on to check if there were other differences between the input assembly and the output plasmid fasta file and out of 2170 headers I had 1464 inaccuracies. 

I don't believe this is an issue with plaSquid as I tested 10 other assemblies and they were completely fine. I will be grateful if you give me some directions on what to test/change.

So far I tested a second assembly with the same assembler (megahit) and I also tried it with a clean install of plaSquid and this specific sample continues to switch headers around.)

Here's a link to the input assembly and the output files from the tool. If you could replicate the case, it would be progress. I also added a simple python script that compares both fasta files and prints the mismatches. 

https://drive.google.com/drive/folders/1FwL41IjDZngpDrKjgJ503h8yxfmIHWHI?usp=sharing

**Comment by mgimenez720** [comment]
Hello, thank you for writing, I hope I can help you with this issue. I have ran plaSquid on your metagenomic assembly (S8_contigs.fasta) and I am having a different result from the one you uploaded. I obtained 2872 contigs instead of 2170 and as far as I could see headers and sequences are the same as in the assembly file.

PlaSquid changes the name of the headers (contig-1, ..., contig-n) so it doesn't have to deal with the header's format of different assemblers, then it restablishes the headers from the original contigs file. It uses Biostrings R package to deal with headers and fasta files. 

The last problem we had is that PLSDB was updated a few months ago and the name of some plasmids changed. May be you should check if PLSDB version is not being recycled from previous installations, that might be causing some errors.   

I will re install and run again to check if there are any inconcistencies in the results I obtain.

**Comment by maddne** [comment]
Thank you for giving this a run. I re-installed plaSquid again (third time) and created a new assembly and it worked well. I have no idea what was wrong with the previous installations. The number of contigs and their headers are correct. I still receive the faulty line in the tsv file at the end - "ig-27077". 
Anyway, you can close the issue. The fasta headers problem seems to be on my end.

**Comment by mgimenez720** [comment]
Thank you for the feedback, I will keep an eye on table missformating issues.
